Repository AdobeDocs/commerce-extensibility, pull requests merged in 2023-10, with the labels that each got.

#79 Add use cases topic
  src/pages/webhooks/use-cases.md
Labels: internal, new topic

#81 Release notes for SDK 1.1.1
  src/pages/admin-ui-sdk/release-notes.md
Labels: internal, major update

#80 Webhooks review draft
  src/data/navigation/sections/webhooks.js
  src/pages/_images/webhooks.png
  src/pages/index.md
  src/pages/webhooks/commands.md
  src/pages/webhooks/hooks.md
  src/pages/webhooks/index.md
  src/pages/webhooks/installation.md
  src/pages/webhooks/responses.md
  src/pages/webhooks/testing.md
  src/pages/webhooks/use-cases.md
  src/pages/webhooks/xml-schema.md
Labels: internal, new topic

#85 Merge webhooks docs into main
  src/data/navigation/header.js
  src/data/navigation/sections/index.js
  src/data/navigation/sections/webhooks.js
  src/pages/_images/webhooks.png
  src/pages/index.md
  src/pages/webhooks/commands.md
  src/pages/webhooks/hooks.md
  src/pages/webhooks/index.md
  src/pages/webhooks/installation.md
  src/pages/webhooks/release-notes.md
  src/pages/webhooks/responses.md
  src/pages/webhooks/testing.md
  src/pages/webhooks/use-cases.md
  src/pages/webhooks/xml-schema.md
Labels: internal, new topic

#86 Instruction on how to install ece-tools from git
  src/pages/webhooks/installation.md
Labels: internal, technical

#87 Fix .md link syntax
  src/pages/webhooks/testing.md
Labels: editorial, internal

#88 Revert "Instruction on how to install ece-tools from git"
  src/pages/webhooks/installation.md
Labels: maintenance, internal

#89 Admin SDK UI 1.2.0 docs
  src/data/navigation/sections/admin-ui-sdk.js
  src/pages/admin-ui-sdk/app-registration.md
  src/pages/admin-ui-sdk/configuration.md
  src/pages/admin-ui-sdk/extension-points/menu.md
  src/pages/admin-ui-sdk/extension-points/order.md
  src/pages/admin-ui-sdk/extension-points/product.md
  src/pages/admin-ui-sdk/release-notes.md
Labels: internal, new topic

#93 Admin UI SDK 1.2.1
  src/pages/_images/sdk-config.png
  src/pages/admin-ui-sdk/configuration.md
  src/pages/admin-ui-sdk/extension-points/order.md
  src/pages/admin-ui-sdk/release-notes.md
Labels: internal, major update
