Repository AdobeDocs/commerce-extensibility, pull requests merged in 2023-05, with the labels that each got.

#15 Add autodeployment
  .github/workflows/deploy.yml
  .github/workflows/publish.yml
  .github/workflows/stage.yml
Labels: enhancement

#20 Add stub files and navigation for SDK and ASC docs
  src/data/navigation/header.js
  src/data/navigation/sections/admin-ui-sdk.js
  src/data/navigation/sections/amazon-sales-channel.js
  src/data/navigation/sections/backoffice.js
  src/data/navigation/sections/index.js
  src/pages/admin-ui-sdk/app-development.md
  src/pages/admin-ui-sdk/configuration.md
  src/pages/admin-ui-sdk/index.md
  src/pages/admin-ui-sdk/installation.md
  src/pages/admin-ui-sdk/reference/menu-app.md
  src/pages/admin-ui-sdk/reference/page-app.md
  src/pages/admin-ui-sdk/release-notes.md
  src/pages/amazon-sales-channel/best-practices/index.md
  src/pages/amazon-sales-channel/index.md
  src/pages/amazon-sales-channel/installation.md
  src/pages/amazon-sales-channel/release-notes.md
  src/pages/backoffice/index.md
Labels: maintenance, internal

#21 Add missing script
  .github/scripts/get-path-prefix.js
Labels: maintenance
