Repository AdobeDocs/commerce-extensibility, pull requests merged in 2023-06, with the labels that each got.

#22 Add intro and installation topics
  src/pages/_images/admin-ui-sdk-architecture.png
  src/pages/_images/admin-ui-sdk-architecture.svg
  src/pages/_images/admin-ui-sequence-diagram.png
  src/pages/_images/sdk-general-configuration.png
  src/pages/admin-ui-sdk/index.md
  src/pages/admin-ui-sdk/installation.md
Labels: internal, new topic

#26 Add top nav and SDK topic
  src/data/navigation/header.js
  src/data/navigation/sections/admin-ui-sdk.js
  src/data/navigation/sections/app-development.js
  src/data/navigation/sections/index.js
  src/pages/amazon-sales-channel/troubleshooting.md
  src/pages/app-development/index.md
Labels: maintenance, internal

#27 Move troubleshooting file
  src/pages/admin-ui-sdk/troubleshooting.md
Labels: internal, major update

#25 Update App development documentation for Admin UI SDK
  src/pages/admin-ui-sdk/app-development.md
Labels: internal, new topic

#24 ASC intro
  src/pages/amazon-sales-channel/index.md
Labels: internal, new topic

#29 Complete the Troubleshooting page for Admin UI SDK documentation
  src/pages/admin-ui-sdk/troubleshooting.md
Labels: internal, new topic

#33 Replace the repo front page
  src/data/navigation/header.js
  src/data/navigation/sections/admin-ui-sdk.js
  src/pages/admin-ui-sdk/app-registration.md
  src/pages/amazon-sales-channel/index.md
  src/pages/index.md
Labels: internal, new topic

#37 Review comments
  src/pages/amazon-sales-channel/index.md
Labels: editorial, internal

#36 Add local testing topic
  src/data/navigation/sections/admin-ui-sdk.js
  src/pages/_images/fetched-orders.png
  src/pages/_images/sdk-config.png
  src/pages/_images/sdk-general-configuration.png
  src/pages/admin-ui-sdk/configuration.md
Labels: internal, new topic

#34 Add ASC installation instructions
  src/data/navigation/sections/amazon-sales-channel.js
  src/pages/amazon-sales-channel/installation.md
  src/pages/amazon-sales-channel/prerequisites.md
Labels: internal, new topic

#38 Add Developer intro
  src/data/navigation/sections/app-development.js
  src/pages/app-development/index.md
Labels: internal, new topic

#35 Add production deployment workflow
  .github/workflows/publish.yml
Labels: maintenance

#41 Add indexing workflow
  .github/workflows/index.yml
Labels: maintenance

#42 Fix xml code sample
  src/pages/amazon-sales-channel/installation.md
Labels: internal, technical

#45 Add links to repo
  src/pages/amazon-sales-channel/index.md
  src/pages/amazon-sales-channel/installation.md
Labels: editorial, internal
