Repository AdobeDocs/commerce-extensibility, pull requests merged in 2023-08, with the labels that each got.

#54 Update dependency version
  src/pages/admin-ui-sdk/app-registration.md
Labels: editorial, internal

#56 Update ASC app prereqs
  src/pages/amazon-sales-channel/installation.md
  src/pages/amazon-sales-channel/prerequisites.md
Labels: editorial, internal

#59 Add extension point docs
  src/data/navigation/sections/admin-ui-sdk.js
  src/pages/_images/sdk-config.png
  src/pages/admin-ui-sdk/app-registration.md
  src/pages/admin-ui-sdk/configuration.md
  src/pages/admin-ui-sdk/extension-points/index.md
  src/pages/admin-ui-sdk/extension-points/menu.md
  src/pages/admin-ui-sdk/extension-points/page.md
  src/pages/admin-ui-sdk/extension-points/product.md
  src/pages/admin-ui-sdk/installation.md
  src/pages/admin-ui-sdk/release-notes.md
Labels: internal, new topic

#61 Admin UI SDK 1.1.0
  src/data/navigation/sections/admin-ui-sdk.js
  src/pages/_images/sdk-config.png
  src/pages/admin-ui-sdk/app-registration.md
  src/pages/admin-ui-sdk/configuration.md
  src/pages/admin-ui-sdk/extension-points/index.md
  src/pages/admin-ui-sdk/extension-points/menu.md
  src/pages/admin-ui-sdk/extension-points/page.md
  src/pages/admin-ui-sdk/extension-points/product.md
  src/pages/admin-ui-sdk/installation.md
  src/pages/admin-ui-sdk/reference/menu-app.md
  src/pages/admin-ui-sdk/reference/page-app.md
  src/pages/admin-ui-sdk/release-notes.md
Labels: internal, new topic

#62 Migrate events content to this repo
  src/data/navigation/header.js
  src/data/navigation/sections/events.js
  src/data/navigation/sections/index.js
  src/pages/_images/events/add-another-api.png
  src/pages/_images/events/add-api.png
  src/pages/_images/events/add-credentials.png
  src/pages/_images/events/add-event.png
  src/pages/_images/events/add-event2.png
  src/pages/_images/events/add-io-management.png
  src/pages/_images/events/adobe-io-events.png
  src/pages/_images/events/browse-templates.png
  src/pages/_images/events/choose-event-subscriptions.png
  src/pages/_images/events/commerce-events.png
  src/pages/_images/events/commerce-instance-selected.png
  src/pages/_images/events/config-event-registration.png
  src/pages/_images/events/create-jwt.png
  src/pages/_images/events/create-project.png
  src/pages/_images/events/download-workspace-config.png
  src/pages/_images/events/event-architecture.png
  src/pages/_images/events/event-list.png
  src/pages/_images/events/event-registration details.png
  src/pages/_images/events/general-configuration.png
  src/pages/_images/events/generate-key-pair.png
  src/pages/_images/events/select-runtime-action.png
  src/pages/_images/events/set-up-templated-project.png
  src/pages/_images/events/setup-api-oauth.png
  src/pages/_images/events/stage-add-api.png
  src/pages/_images/events/workspaces.png
  src/pages/amazon-sales-channel/installation.md
  src/pages/amazon-sales-channel/prerequisites.md
  src/pages/app-development/index.md
  src/pages/events/commands.md
  src/pages/events/conditional-events.md
  src/pages/events/configure-commerce.md
  src/pages/events/custom-event-fields.md
  src/pages/events/index.md
  src/pages/events/installation.md
  src/pages/events/module-development.md
  src/pages/events/project-setup.md
  src/pages/events/release-notes.md
  src/pages/index.md
Labels: maintenance, internal

#63 Fix composer require backend-uix command
  src/pages/admin-ui-sdk/installation.md
Labels: editorial, internal
