Repository AdobeDocs/commerce-extensibility, pull requests merged in 2023-12, with the labels that each got.

#120 Add step to eventing update procedure
  src/pages/events/installation.md
Labels: internal, technical

#123 Fix the failing GH workflows
  .github/workflows/github-pages.yml
  .github/workflows/index.yml
  .github/workflows/publish.yml
  .github/workflows/stage.yml
  .nvmrc
  package.json
  src/pages/amazon-sales-channel/index.md
Labels: maintenance

#124 Remove discussion of installing ASC
  src/pages/amazon-sales-channel/index.md
Labels: editorial, internal

#122 Docs update for 1.4.1 eventing release
  src/pages/events/installation.md
  src/pages/events/release-notes.md
Labels: internal, major-update

#126 Update URL
  src/pages/app-development/examples.md
Labels: maintenance, internal

#127 Update steps for selecting an event provider in App Builder UI
  src/pages/_images/events/select-commerce-event.png
  src/pages/events/configure-commerce.md
Labels: internal, technical
