Repository AdobeDocs/commerce-extensibility, pull requests merged in 2023-11, with the labels that each got.

#94 Fix indexing
  .github/workflows/index.yml
Labels: bug, maintenance

#95 Fix wrong module names
  src/pages/webhooks/installation.md
Labels: technical

#96 Update installation steps for commerce eventing
  src/pages/events/installation.md
Labels: internal, technical

#99 Update workflows with deployments
  .github/workflows/publish.yml
  .github/workflows/stage.yml
Labels: maintenance

#100 Sync deployment workflows
  .github/workflows/publish.yml
  .github/workflows/stage.yml
Labels: maintenance

#98 CEXT-2482: Add support of nested fields to the eventing rules
  src/pages/_images/events/commerce-events.png
  src/pages/events/commands.md
  src/pages/events/conditional-events.md
  src/pages/events/configure-commerce.md
  src/pages/events/custom-event-fields.md
  src/pages/events/module-development.md
  src/pages/events/release-notes.md
Labels: internal

#103 Fix typo on landing page
  src/pages/index.md
Labels: editorial, internal

#102 CEXT-2484: Document new operations
  src/pages/webhooks/responses.md
  src/pages/webhooks/use-cases.md
Labels: internal, major update

#105 CEXT-2534: Documenting array-type field filtering
  src/pages/webhooks/hooks.md
Labels: internal, technical

#108 Add Webhooks keyword
  .github/linters/metadata.schema.yml
Labels: maintenance, internal

#107 Add a linter to validate external links
  .remarkrc.mjs
  package.json
  yarn.lock
Labels: enhancement

#106 CEXT-2542: Document the conditional webhooks
  src/pages/events/conditional-events.md
  src/pages/webhooks/conditional-webhooks.md
Labels: internal, new topic

#109 Add validation for custom headers
  .remarkrc.mjs
  package.json
  yarn.lock
Labels: bug, enhancement

#113 Add nav for custom webhooks
  src/data/navigation/sections/webhooks.js
  src/pages/webhooks/conditional-webhooks.md
Labels: editorial, internal

#112 Update theme and caniuse-lite
  package.json
  yarn.lock
Labels: dependencies

#115 Eventing 1.4.0 release notes
  src/pages/events/installation.md
  src/pages/events/release-notes.md
Labels: internal, major update

#114 Webhooks 1.1 release notes and update
  src/pages/webhooks/installation.md
  src/pages/webhooks/release-notes.md
Labels: internal, major update

#117 SDK 1.3.0 release notes
  src/pages/admin-ui-sdk/release-notes.md
Labels: internal, major update

#111 Merge webhooks development branch into main
  .github/linters/metadata.schema.yml
  src/data/navigation/sections/webhooks.js
  src/pages/events/conditional-events.md
  src/pages/webhooks/conditional-webhooks.md
  src/pages/webhooks/hooks.md
  src/pages/webhooks/installation.md
  src/pages/webhooks/release-notes.md
  src/pages/webhooks/responses.md
  src/pages/webhooks/testing.md
  src/pages/webhooks/use-cases.md
  src/pages/webhooks/xml-schema.md
Labels: maintenance, internal

#116 Merge events-develop into main
  src/pages/_images/events/commerce-events.png
  src/pages/events/commands.md
  src/pages/events/conditional-events.md
  src/pages/events/configure-commerce.md
  src/pages/events/custom-event-fields.md
  src/pages/events/installation.md
  src/pages/events/module-development.md
  src/pages/events/release-notes.md
  src/pages/webhooks/index.md
Labels: maintenance, internal

#118 Extension points
  src/data/navigation/sections/admin-ui-sdk.js
  src/pages/admin-ui-sdk/extension-points/index.md
  src/pages/admin-ui-sdk/extension-points/order/grid-columns.md
  src/pages/admin-ui-sdk/extension-points/order/index.md
  src/pages/admin-ui-sdk/extension-points/order/mass-action.md
  src/pages/admin-ui-sdk/extension-points/order/view-button.md
  src/pages/admin-ui-sdk/extension-points/product/grid-columns.md
  src/pages/admin-ui-sdk/extension-points/product/index.md
  src/pages/admin-ui-sdk/extension-points/product/mass-action.md
  src/pages/admin-ui-sdk/release-notes.md
Labels: internal, new topic

#119 Merge sdk130-develop into main
  src/data/navigation/sections/admin-ui-sdk.js
  src/pages/admin-ui-sdk/extension-points/index.md
  src/pages/admin-ui-sdk/extension-points/order/grid-columns.md
  src/pages/admin-ui-sdk/extension-points/order/index.md
  src/pages/admin-ui-sdk/extension-points/order/mass-action.md
  src/pages/admin-ui-sdk/extension-points/order/view-button.md
  src/pages/admin-ui-sdk/extension-points/product/grid-columns.md
  src/pages/admin-ui-sdk/extension-points/product/index.md
  src/pages/admin-ui-sdk/extension-points/product/mass-action.md
  src/pages/admin-ui-sdk/release-notes.md
Labels: maintenance, internal
