Repository AdobeDocs/commerce-extensibility, pull requests merged in 2023-09, with the labels that each got.

#64 Clarify frontend development details
  src/pages/app-development/index.md
Labels: editorial, internal

#65 Add runtime actions and New Relic sections
  src/pages/amazon-sales-channel/best-practices/logging-troubleshooting.md
Labels: editorial, internal

#67 COMDOX-345: Add missing metadata
  src/pages/admin-ui-sdk/app-registration.md
  src/pages/admin-ui-sdk/configuration.md
  src/pages/admin-ui-sdk/extension-points/index.md
  src/pages/admin-ui-sdk/extension-points/menu.md
  src/pages/admin-ui-sdk/extension-points/page.md
  src/pages/admin-ui-sdk/extension-points/product.md
  src/pages/admin-ui-sdk/index.md
  src/pages/admin-ui-sdk/installation.md
  src/pages/admin-ui-sdk/release-notes.md
  src/pages/admin-ui-sdk/troubleshooting.md
  src/pages/amazon-sales-channel/best-practices/credentials.md
  src/pages/amazon-sales-channel/best-practices/database-storage.md
  src/pages/amazon-sales-channel/best-practices/index.md
  src/pages/amazon-sales-channel/best-practices/logging-troubleshooting.md
  src/pages/amazon-sales-channel/index.md
  src/pages/amazon-sales-channel/installation.md
  src/pages/amazon-sales-channel/prerequisites.md
  src/pages/amazon-sales-channel/release-notes.md
  src/pages/app-development/index.md
  src/pages/events/commands.md
  src/pages/events/conditional-events.md
  src/pages/events/configure-commerce.md
  src/pages/events/custom-event-fields.md
  src/pages/events/index.md
  src/pages/events/installation.md
  src/pages/events/module-development.md
  src/pages/events/project-setup.md
  src/pages/events/release-notes.md
  src/pages/index.md
Labels: maintenance, internal

#68 COMDOX-345: Added validation test for metadata
  .github/linters/metadata.schema.yml
  .remarkrc.mjs
  package.json
  src/pages/amazon-sales-channel/best-practices/logging-troubleshooting.md
  yarn.lock
Labels: maintenance

#55 Extensibility Examples
  src/data/navigation/sections/app-development.js
  src/pages/_images/api-mesh-diagram.mmd
  src/pages/_images/api-mesh-diagram.png
  src/pages/_images/integrated-commerce.mmd
  src/pages/_images/integrated-commerce.png
  src/pages/app-development/examples.md
  src/pages/index.md
Labels: major update, new topic

#70 Fix the release date of Events 1.3.0
  src/pages/events/release-notes.md
Labels: editorial, internal

#66 Add publishing topic
  src/data/navigation/sections/admin-ui-sdk.js
  src/pages/admin-ui-sdk/publish.md
  src/pages/admin-ui-sdk/release-notes.md
Labels: internal, new topic

#71 Add Webhooks stub files/nav
  src/data/navigation/header.js
  src/data/navigation/sections/index.js
  src/data/navigation/sections/webhooks.js
  src/pages/webhooks/commands.md
  src/pages/webhooks/index.md
  src/pages/webhooks/installation.md
  src/pages/webhooks/release-notes.md
Labels: maintenance, internal

#73 Add examples for CLI commands and installation steps
  src/pages/webhooks/commands.md
  src/pages/webhooks/installation.md
Labels: internal, major update

#74 Add examples of webhooks and xml schema description
  src/pages/webhooks/index.md
Labels: internal, major update

#76 Fix community engineering slack channel link
  src/pages/amazon-sales-channel/index.md
Labels: editorial, internal

#78 Update context fields documentation
  src/pages/webhooks/index.md
Labels: internal
