Repository AdobeDocs/commerce-extensibility, pull requests merged in 2024-08, with the labels that each got.

#252 Add link to Starter Kit tutorials
  src/data/navigation/sections/starter-kit.js
Labels: editorial, internal

#259 Set matching languages in CodeBlock
  src/pages/app-development/examples.md
  src/pages/starter-kit/events.md
  src/pages/starter-kit/receive-data.md
  src/pages/starter-kit/webhooks.md
Labels: editorial

#260 [ImgBot] Optimize images
  src/pages/_images/events/general-configuration-empty.png
  src/pages/_images/events/general-configuration-instanceId.png
  src/pages/_images/events/general-configuration-providerId-adminui.png
  src/pages/_images/events/general-configuration-providerId-cli.png
  src/pages/_images/events/general-configuration-providerInfo.png
  src/pages/_images/events/general-configuration-updated.png
Labels: editorial

#261 Refactor GitHub Actions workflows
  .github/super-linter.env
  .github/workflows/github-pages.yml
  .github/workflows/index.yml
  .github/workflows/publish.yml
  .github/workflows/stage.yml
  .github/workflows/test-pull-request.yml
Labels: maintenance, internal

#263 Fix typo
  src/pages/starter-kit/ms-finance.md
Labels: editorial
