Repository AdobeDocs/commerce-extensibility, pull requests merged in 2024-01, with the labels that each got.

#128 Add note about generating fixtures
  src/pages/events/commands.md
Labels: internal, technical

#132 CEXT-2645: Create a troubleshooting documentation page
  src/data/navigation/sections/events.js
  src/pages/_images/events/instance-name-developer-commerce.png
  src/pages/_images/events/instance-name-developer-console.png
  src/pages/admin-ui-sdk/app-registration.md
  src/pages/events/troubleshooting.md
Labels: internal, new-topic

#131 CEXT-1699 Draft version
  src/data/navigation/sections/events.js
  src/pages/admin-ui-sdk/app-registration.md
  src/pages/events/commands.md
  src/pages/events/convert-field-values.md
  src/pages/events/module-development.md
Labels: new-topic

#134 SDK 1.3.1 release notes
  src/pages/admin-ui-sdk/extension-points/order/mass-action.md
  src/pages/admin-ui-sdk/extension-points/product/mass-action.md
  src/pages/admin-ui-sdk/release-notes.md
Labels: internal, major-update

#141 Correct order view parameters
  src/pages/admin-ui-sdk/extension-points/order/view-button.md
Labels: internal, technical

#142 Remove class from order button
  src/pages/admin-ui-sdk/extension-points/order/view-button.md
Labels: technical
