Repository AdobeDocs/commerce-extensibility, pull requests merged in 2024-05, with the labels that each got.

#199 Add reference to info action
  src/pages/starter-kit/create-integration.md
Labels: editorial, internal

#200 Update product name
  src/_includes/integration.md
  src/_includes/starter-kit-beta.md
  src/pages/starter-kit/best-practices.md
  src/pages/starter-kit/contact-us.md
  src/pages/starter-kit/create-integration.md
  src/pages/starter-kit/customers.md
  src/pages/starter-kit/data-flows.md
  src/pages/starter-kit/developer-tools.md
  src/pages/starter-kit/events.md
  src/pages/starter-kit/index.md
  src/pages/starter-kit/orders.md
  src/pages/starter-kit/products.md
  src/pages/starter-kit/receive-data.md
  src/pages/starter-kit/shipments.md
  src/pages/starter-kit/stock.md
  src/pages/starter-kit/structure.md
  src/pages/starter-kit/use-cases.md
  src/pages/starter-kit/webhooks.md
Labels: editorial, internal

#203 Update left nav
  src/data/navigation/sections/starter-kit.js
Labels: editorial, internal

#204 CEXT-3206: Release commerce webhooks and eventing module
  src/data/navigation/sections/webhooks.js
  src/pages/_images/webhooks/signature-configuration.png
  src/pages/events/commands.md
  src/pages/events/release-notes.md
  src/pages/webhooks/release-notes.md
  src/pages/webhooks/signature-verification.md
Labels: enhancement, new-topic

#201 Do not merge till GA: Remove beta notice
  src/pages/starter-kit/best-practices.md
  src/pages/starter-kit/contact-us.md
  src/pages/starter-kit/create-data-flow.md
  src/pages/starter-kit/create-integration.md
  src/pages/starter-kit/customers.md
  src/pages/starter-kit/data-flows.md
  src/pages/starter-kit/developer-tools.md
  src/pages/starter-kit/events.md
  src/pages/starter-kit/index.md
  src/pages/starter-kit/launch.md
  src/pages/starter-kit/orders.md
  src/pages/starter-kit/products.md
  src/pages/starter-kit/receive-data.md
  src/pages/starter-kit/send-data.md
  src/pages/starter-kit/shipments.md
  src/pages/starter-kit/stock.md
  src/pages/starter-kit/structure.md
  src/pages/starter-kit/use-cases.md
Labels: editorial

#202 Add location of starter kit location
  src/pages/starter-kit/create-integration.md
Labels: editorial, internal

#211 Update Admin UI SDK configuration and testing page
  src/pages/admin-ui-sdk/configuration.md
Labels: editorial

#206 Add order custom fees extension point
  src/data/navigation/sections/admin-ui-sdk.js
  src/pages/admin-ui-sdk/extension-points/order/custom-fees.md
  src/pages/admin-ui-sdk/release-notes.md
Labels: new-topic

#213 CEXT-3242: Release the new version of commerce webhooks without admin UI
  src/pages/_images/webhooks/edit-hook-fields.png
  src/pages/_images/webhooks/edit-hook-settings.png
  src/pages/_images/webhooks/new-hook-settings.png
  src/pages/_images/webhooks/webhooks-grid.png
  src/pages/starter-kit/webhooks.md
  src/pages/webhooks/admin-configuration.md
  src/pages/webhooks/release-notes.md
Labels: bug, editorial

#215 cleanup
  src/data/navigation/sections/starter-kit.js
  src/pages/starter-kit/webhooks.md
  src/pages/webhooks/release-notes.md
Labels: editorial

#217 CEXT-2855: Provide context to Commerce Configuration fields in onboarding docs
  src/pages/_images/events/general-configuration-updated.png
  src/pages/app-development/amazon-sales-channel/prerequisites.md
  src/pages/events/configure-commerce.md
Labels: internal, technical

#209 Starter kit support
  src/pages/starter-kit/create-integration.md
Labels: editorial
