Repository AdobeDocs/commerce-extensibility, pull requests merged in 2024-03, with the labels that each got.

#157 SDK 1.3.2 release notes
  src/pages/admin-ui-sdk/release-notes.md
Labels: internal, major-update

#161 Webhooks 1.2.1 release notes
  src/pages/_images/webhooks/webhooks-grid.png
  src/pages/webhooks/release-notes.md
Labels: internal, major-update

#164 Update Adobe IO State Library details
  src/pages/amazon-sales-channel/best-practices/database-storage.md
Labels: internal, technical

#156 Webhooks
  src/data/navigation/sections/app-development.js
  src/pages/app-development/starter-kit/ingestion-webhook.md
  src/pages/app-development/starter-kit/project-setup.md
  src/pages/app-development/starter-kit/webhooks-example.md
Labels: new-topic
