Repository AdobeDocs/commerce-extensibility, pull requests merged in 2024-04, with the labels that each got.

#171 Fix typo
  src/pages/webhooks/index.md
Labels: documentation, internal

#170 Upgrade theme to v4.11.9
  package.json
  yarn.lock
Labels: dependencies, internal

#165 CEXT-2912: Add API to commerce eventing for configuring the module
  src/data/navigation/sections/events.js
  src/pages/events/api.md
Labels: internal, new-topic

#172 CEXT-2990: Release commerce eventing modules 1.6.0
  src/pages/events/release-notes.md
Labels: internal, major-update

#177 Fit the request method type
  src/pages/events/api.md
Labels: editorial, internal

#186 CEXT-3055: Release commerce webhooks 1.3.0
  src/pages/webhooks/release-notes.md
Labels: internal, major-update

#187 Return of the App Development section
  src/_includes/integration.md
  src/data/navigation/header.js
  src/data/navigation/sections/app-development.js
  src/data/navigation/sections/index.js
  src/data/navigation/sections/starter-kit.js
  src/pages/starter-kit/best-practices.md
  src/pages/starter-kit/code-samples/data-customer-group.md
  src/pages/starter-kit/code-samples/data-customer.md
  src/pages/starter-kit/code-samples/data-order.md
  src/pages/starter-kit/code-samples/data-product.md
  src/pages/starter-kit/code-samples/data-shipment.md
  src/pages/starter-kit/code-samples/data-stock.md
  src/pages/starter-kit/code-samples/incoming-customer-group.md
  src/pages/starter-kit/code-samples/incoming-customer.md
  src/pages/starter-kit/code-samples/incoming-order.md
  src/pages/starter-kit/code-samples/incoming-product.md
  src/pages/starter-kit/code-samples/incoming-shipment.md
  src/pages/starter-kit/code-samples/incoming-stock.md
  src/pages/starter-kit/contact-us.md
  src/pages/starter-kit/create-data-flow.md
  src/pages/starter-kit/customers.md
  src/pages/starter-kit/developer-tools.md
  src/pages/starter-kit/dummy.md
  src/pages/starter-kit/events.md
  src/pages/starter-kit/index.md
  src/pages/starter-kit/launch.md
  src/pages/starter-kit/orders.md
  src/pages/starter-kit/products.md
  src/pages/starter-kit/receive-data.md
  src/pages/starter-kit/send-data.md
  src/pages/starter-kit/shipments.md
  src/pages/starter-kit/stock.md
  src/pages/starter-kit/structure.md
  src/pages/starter-kit/use-cases.md
  src/pages/starter-kit/webhooks.md
Labels: editorial, internal

#189 Index file work
  src/data/navigation/sections/starter-kit.js
  src/pages/app-development/index.md
  src/pages/starter-kit/create-integration.md
  src/pages/starter-kit/dummy.md
  src/pages/starter-kit/index.md
  src/pages/starter-kit/structure.md
  src/pages/starter-kit/webhooks.md
Labels: editorial, internal

#190 Add missing beta notices
  src/_includes/starter-kit-beta.md
  src/data/navigation/sections/starter-kit.js
  src/pages/starter-kit/contact-us.md
  src/pages/starter-kit/create-data-flow.md
  src/pages/starter-kit/customers.md
  src/pages/starter-kit/index.md
  src/pages/starter-kit/launch.md
  src/pages/starter-kit/orders.md
  src/pages/starter-kit/products.md
  src/pages/starter-kit/receive-data.md
  src/pages/starter-kit/shipments.md
  src/pages/starter-kit/stock.md
  src/pages/starter-kit/structure.md
Labels: editorial, internal

#191 Add topnav link to Mesh
  src/data/navigation/header.js
Labels: editorial, internal

#195 Attempts to fix nav
  src/data/navigation/header.js
  src/data/navigation/sections/starter-kit.js
  src/pages/app-development/learning-path.md
Labels: maintenance, internal

#198 Data flows overview
  src/data/navigation/sections/starter-kit.js
  src/pages/_images/starterkit/data-flow.png
  src/pages/starter-kit/data-flows.md
  src/pages/starter-kit/index.md
Labels: new-topic
