Repository AdobeDocs/commerce-extensibility, pull requests merged in 2024-07, with the labels that each got.

#238 Fix broken relative links
  src/data/navigation/sections/admin-ui-sdk.js
  src/pages/admin-ui-sdk/extension-points/customer/mass-action.md
  src/pages/admin-ui-sdk/extension-points/order/mass-action.md
  src/pages/admin-ui-sdk/extension-points/product/mass-action.md
Labels: bug, internal

#242 remove shipments from starter-kit-registrations.json code sample
  src/pages/starter-kit/create-integration.md
Labels: internal, technical

#246 Upgrade devDependencies
  .remarkrc.mjs
  package.json
  yarn.lock
Labels: dependencies

#247 Add links to code sample repo
  src/data/navigation/sections/starter-kit.js
  src/pages/starter-kit/create-integration.md
  src/pages/starter-kit/events.md
Labels: editorial, internal

#248 Enable indexing on deploy
  .github/workflows/index.yml
  .github/workflows/publish.yml
Labels: maintenance, internal

#251 Merge 180-develop into main
  src/pages/_images/events/general-configuration-updated.png
  src/pages/_images/events/general-configuration.png
  src/pages/events/commands.md
  src/pages/events/configure-commerce.md
Labels: maintenance, internal
