Repository AdobeDocs/commerce-extensibility, pull requests merged in 2024-12, with the labels that each got.

#294 CEXT-3897: Documentation update for webhooks signature verification
  src/pages/webhooks/signature-verification.md
Labels: internal, technical

#299 Broken link
  src/pages/_images/events/general-configuration-updated.png
  src/pages/_images/events/instance-name-developer-commerce.png
  src/pages/events/configure-commerce.md
  src/pages/events/consume-events-examples/runtime-action-commerce-callback.md
  src/pages/events/troubleshooting.md
  src/pages/starter-kit/create-integration.md
Labels: editorial, internal

#300 Update GitHub workflows
  .github/workflows/publish.yml
  .github/workflows/stage.yml
  .github/workflows/test-pull-request.yml
  package.json
Labels: maintenance, internal

#303 CEXT-3976: Release commerce-webhooks 1.7.0
  src/pages/webhooks/release-notes.md
Labels: internal, major-update

#304 Add Admin UI SDK 2.1.1 release notes
  src/pages/admin-ui-sdk/release-notes.md
Labels: internal
