Repository AdobeDocs/commerce-extensibility, pull requests merged in 2024-02, with the labels that each got.

#143 CEXT-2783: Documentation on how to resolve stuck deployment on the Cloud
  src/pages/events/configure-commerce.md
  src/pages/events/troubleshooting.md
Labels: internal, technical

#148 Webhooks 1.2.0 release notes
  src/pages/webhooks/release-notes.md
Labels: internal, major-update

#147 CEXT-2829: Draft of webhooks admin UI docs page
  src/data/navigation/sections/webhooks.js
  src/pages/_images/webhooks/edit-hook-fields.png
  src/pages/_images/webhooks/edit-hook-settings.png
  src/pages/_images/webhooks/webhooks-grid.png
  src/pages/webhooks/admin-configuration.md
  src/pages/webhooks/release-notes.md
Labels: internal, new-topic

#150 Merge webhooks develop branch into main
  src/data/navigation/sections/webhooks.js
  src/pages/_images/webhooks/edit-hook-fields.png
  src/pages/_images/webhooks/edit-hook-settings.png
  src/pages/_images/webhooks/webhooks-grid.png
  src/pages/webhooks/admin-configuration.md
  src/pages/webhooks/release-notes.md
Labels: maintenance, internal

#151 Webhooks admin configuration warning addition
  src/pages/webhooks/admin-configuration.md
Labels: editorial, internal

#152 Add Admin configuraiton details
  src/pages/_images/webhooks/new-hook-settings.png
  src/pages/events/commands.md
  src/pages/webhooks/admin-configuration.md
  src/pages/webhooks/commands.md
  src/pages/webhooks/conditional-webhooks.md
  src/pages/webhooks/release-notes.md
  src/pages/webhooks/testing.md
  src/pages/webhooks/xml-schema.md
Labels: editorial, internal

#104 In-process vs out-of-process extensibility
  src/data/navigation/sections/app-development.js
  src/pages/_images/extensibility-strategy-overview.png
  src/pages/app-development/learning-path.md
  src/pages/index.md
Labels: internal, major-update, new-topic

#153 Reorder sections on front page
  src/pages/index.md
Labels: editorial, internal

#154 Add logging to learning path
  src/pages/app-development/learning-path.md
Labels: editorial, internal

#155 Starter Kit installation/setup
  src/_includes/project-requirements.md
  src/data/navigation/sections/app-development.js
  src/pages/_images/common/add-another-api.png
  src/pages/_images/common/add-io-management.png
  src/pages/_images/common/create-project.png
  src/pages/_images/common/set-up-templated-project.png
  src/pages/_images/common/setup-api-oauth.png
  src/pages/_images/common/stage-add-api.png
  src/pages/_images/common/workspaces.png
  src/pages/_images/starterkit/activate-integration.png
  src/pages/_images/starterkit/add-integration.png
  src/pages/_images/starterkit/integrations-resources.png
  src/pages/_images/starterkit/registrations.png
  src/pages/_images/starterkit/runtime-actions.png
  src/pages/_images/starterkit/secrets.png
  src/pages/app-development/starter-kit/index.md
  src/pages/app-development/starter-kit/project-setup.md
  src/pages/events/project-setup.md
Labels: internal, new-topic

#144 runtime actions
  src/data/navigation/sections/app-development.js
  src/pages/app-development/starter-kit/code-samples/data-customer-group.md
  src/pages/app-development/starter-kit/code-samples/data-customer.md
  src/pages/app-development/starter-kit/code-samples/data-order.md
  src/pages/app-development/starter-kit/code-samples/data-product.md
  src/pages/app-development/starter-kit/code-samples/data-shipment.md
  src/pages/app-development/starter-kit/code-samples/data-stock.md
  src/pages/app-development/starter-kit/code-samples/incoming-customer-group.md
  src/pages/app-development/starter-kit/code-samples/incoming-customer.md
  src/pages/app-development/starter-kit/code-samples/incoming-order.md
  src/pages/app-development/starter-kit/code-samples/incoming-product.md
  src/pages/app-development/starter-kit/code-samples/incoming-shipment.md
  src/pages/app-development/starter-kit/code-samples/incoming-stock.md
  src/pages/app-development/starter-kit/integration.md
Labels: internal, major-update, new-topic
