Repository AdobeDocs/commerce-extensibility, pull requests merged in 2024-06, with the labels that each got.

#218 CEXT-2856: Add context to event provider in onboarding docs
  src/pages/_images/events/commerce-events.png
  src/pages/_images/events/general-configuration-updated.png
  src/pages/events/configure-commerce.md
Labels: internal, technical

#221 Updating eventing instructions in starter kit
  src/pages/events/configure-commerce.md
  src/pages/starter-kit/create-integration.md
Labels: editorial

#225 MS F&O example app
  .github/linters/metadata.schema.yml
  src/pages/_images/starterkit/FO365.png
  src/pages/starter-kit/best-practices.md
  src/pages/starter-kit/contact-us.md
  src/pages/starter-kit/create-data-flow.md
  src/pages/starter-kit/create-integration.md
  src/pages/starter-kit/customers.md
  src/pages/starter-kit/data-flows.md
  src/pages/starter-kit/developer-tools.md
  src/pages/starter-kit/events.md
  src/pages/starter-kit/launch.md
  src/pages/starter-kit/ms-finance.md
  src/pages/starter-kit/orders.md
  src/pages/starter-kit/products.md
  src/pages/starter-kit/receive-data.md
  src/pages/starter-kit/send-data.md
  src/pages/starter-kit/shipments.md
  src/pages/starter-kit/stock.md
  src/pages/starter-kit/structure.md
  src/pages/starter-kit/use-cases.md
  src/pages/starter-kit/webhooks.md
Labels: new-topic

#219 CEXT-3214: Docs for consuming events
  src/_includes/project-requirements.md
  src/data/navigation/sections/events.js
  src/pages/_images/events/receive-events-options.png
  src/pages/_images/events/register-webhook.png
  src/pages/_images/events/select-runtime-action.png
  src/pages/events/configure-commerce.md
  src/pages/events/consume-events-examples/index.md
  src/pages/events/consume-events-examples/runtime-action-commerce-callback.md
  src/pages/events/consume-events.md
  src/pages/events/project-setup.md
Labels: new-topic

#226 Adding removed section
  src/pages/events/consume-events.md
Labels: editorial

#222 CEXT-2940: Sunset Commerce Events template
  .remarkrc.mjs
  src/pages/events/configure-commerce.md
Labels: major-update

#227 Upgrade theme to v4.11.14
  package.json
  yarn.lock
Labels: dependencies, internal

#228 CEXT-3214: Fixing missing header and typos
  src/pages/events/consume-events-examples/runtime-action-commerce-callback.md
  src/pages/events/consume-events.md
Labels: editorial, internal

#230 Updares to MS Finance topic
  src/data/navigation/sections/starter-kit.js
  src/pages/starter-kit/ms-finance.md
Labels: editorial, internal
