Repository AdobeDocs/commerce-extensibility, pull requests merged in 2025-06, with the labels that each got.

#382 CEXT-4724: Update the minimum Commerce version of Tax to v2.4.6
  src/_includes/checkout-version.md
  src/pages/starter-kit/checkout/getting-started.md
  src/pages/starter-kit/checkout/payment-install.md
  src/pages/starter-kit/checkout/shipping-install.md
  src/pages/starter-kit/checkout/tax-install.md
Labels: editorial

#383 App builder submission guidelines
  src/_includes/webhook-auth.md
  src/data/navigation/sections/app-development.js
  src/pages/app-development/app-submission-guidelines.md
Labels: major-update, new-topic

#392 Alternative testing options for app submission
  src/pages/app-development/app-submission-guidelines.md
Labels: major-update

#394 Add badging for eventing
  src/_includes/conditional-event-example.md
  src/_includes/conditional-event.md
  src/_includes/nested-event.md
  src/_includes/sample-event.md
  src/data/navigation/sections/events.js
  src/pages/events/api.md
  src/pages/events/commands.md
  src/pages/events/conditional-events.md
  src/pages/events/configure-commerce.md
  src/pages/events/convert-field-values.md
  src/pages/events/create-events.md
  src/pages/events/custom-event-fields.md
  src/pages/events/installation.md
  src/pages/events/module-development.md
Labels: maintenance, internal

#395 Cext 4818 app builder compatibility
  src/data/navigation/sections/app-development.js
  src/pages/app-development/app-submission-guidelines.md
  src/pages/app-development/extension-compatibility.md
Labels: major-update

#396 CEXT-4720: Update Checkout Starter Kit configuration steps
  src/_includes/checkout-configuration.md
  src/pages/_images/starterkit/ims-user-creation.png
  src/pages/_images/starterkit/ims-user-role.png
  src/pages/starter-kit/checkout/configure.md
  src/pages/starter-kit/checkout/connect.md
  src/pages/starter-kit/checkout/getting-started.md
  src/pages/starter-kit/checkout/payment-install.md
  src/pages/starter-kit/checkout/shipping-install.md
  src/pages/starter-kit/checkout/tax-install.md
Labels: major-update

#398 Fix typo in heading
  src/pages/webhooks/api.md
Labels: editorial, internal

#399 [Admin UI SDK] update documentation for code layout best practices and clarify extension support
  src/pages/admin-ui-sdk/app-registration.md
  src/pages/admin-ui-sdk/configuration.md
  src/pages/admin-ui-sdk/index.md
Labels: internal, technical

#404 Add statement to custom fields topic
  src/pages/events/custom-event-fields.md
Labels: technical
