Repository AdobeDocs/commerce-extensibility, pull requests merged in 2025-02, with the labels that each got.

#316 Add release notes for Admin UI SDK 2.2.0
  src/pages/admin-ui-sdk/release-notes.md
Labels: documentation, internal

#310 Checkout starter kit
  src/data/navigation/header.js
  src/data/navigation/sections/checkout-starter-kit.js
  src/data/navigation/sections/index.js
  src/data/navigation/sections/integration-starter-kit.js
  src/pages/_images/starterkit/sequence.mmd
  src/pages/_images/starterkit/sequence.png
  src/pages/_images/starterkit/use-case-1.png
  src/pages/_images/starterkit/use-case-2.png
  src/pages/_images/starterkit/use-case-3.png
  src/pages/_images/starterkit/use-cases.mmd
  src/pages/_images/starterkit/userCreation.png
  src/pages/app-development/learning-path.md
  src/pages/events/consume-events.md
  src/pages/starter-kit/checkout/cicd.md
  src/pages/starter-kit/checkout/configure.md
  src/pages/starter-kit/checkout/connect.md
  src/pages/starter-kit/checkout/development.md
  src/pages/starter-kit/checkout/eds.md
  src/pages/starter-kit/checkout/getting-started.md
  src/pages/starter-kit/checkout/index.md
  src/pages/starter-kit/checkout/payment-reference.md
  src/pages/starter-kit/checkout/payment-usage.md
  src/pages/starter-kit/checkout/shipping-reference.md
  src/pages/starter-kit/checkout/use-cases.md
  src/pages/starter-kit/integration/best-practices.md
  src/pages/starter-kit/integration/code-samples/data-customer-group.md
  src/pages/starter-kit/integration/code-samples/data-customer.md
  src/pages/starter-kit/integration/code-samples/data-order.md
  src/pages/starter-kit/integration/code-samples/data-product.md
  src/pages/starter-kit/integration/code-samples/data-shipment.md
  src/pages/starter-kit/integration/code-samples/data-stock.md
  src/pages/starter-kit/integration/code-samples/incoming-customer-group.md
  src/pages/starter-kit/integration/code-samples/incoming-customer.md
  src/pages/starter-kit/integration/code-samples/incoming-order.md
  src/pages/starter-kit/integration/code-samples/incoming-product.md
  src/pages/starter-kit/integration/code-samples/incoming-shipment.md
  src/pages/starter-kit/integration/code-samples/incoming-stock.md
  src/pages/starter-kit/integration/contact-us.md
  src/pages/starter-kit/integration/create-data-flow.md
  src/pages/starter-kit/integration/create-integration.md
  src/pages/starter-kit/integration/customers.md
  src/pages/starter-kit/integration/data-flows.md
  src/pages/starter-kit/integration/developer-tools.md
  src/pages/starter-kit/integration/events.md
  src/pages/starter-kit/integration/index.md
  src/pages/starter-kit/integration/launch.md
  src/pages/starter-kit/integration/ms-finance.md
  src/pages/starter-kit/integration/orders.md
  src/pages/starter-kit/integration/products.md
  src/pages/starter-kit/integration/receive-data.md
  src/pages/starter-kit/integration/send-data.md
  src/pages/starter-kit/integration/shipments.md
  src/pages/starter-kit/integration/stock.md
  src/pages/starter-kit/integration/structure.md
  src/pages/starter-kit/integration/use-cases.md
  src/pages/starter-kit/integration/webhooks.md
  static/payment.graphqls
  static/payment.xml
  static/shipping.graphqls
  static/shipping.xml
Labels: major-update, new-topic

#317 checkout starter kit feedback
  src/data/navigation/sections/checkout-starter-kit.js
  src/data/navigation/sections/integration-starter-kit.js
  src/pages/starter-kit/checkout/index.md
Labels: editorial

#321 Update GitHub workflows
  .github/workflows/publish.yml
  .github/workflows/stage.yml
Labels: maintenance, internal

#324 Update GitHub workflows
  .github/workflows/github-pages.yml
Labels: maintenance, internal

#326 Update GitHub workflows
  .github/workflows/test-pull-request.yml
Labels: maintenance, internal
