Repository AdobeDocs/commerce-extensibility, pull requests merged in 2025-05, with the labels that each got.

#360 checkout reorganization
  src/_includes/checkout-version.md
  src/data/navigation/sections/checkout-starter-kit.js
  src/pages/starter-kit/checkout/configure.md
  src/pages/starter-kit/checkout/getting-started.md
  src/pages/starter-kit/checkout/payment-install.md
  src/pages/starter-kit/checkout/payment-use-cases.md
  src/pages/starter-kit/checkout/shipping-install.md
  src/pages/starter-kit/checkout/shipping-usage.md
  src/pages/starter-kit/checkout/shipping-use-cases.md
  src/pages/starter-kit/checkout/tax-install.md
  src/pages/starter-kit/checkout/tax-use-cases.md
  src/pages/starter-kit/checkout/use-cases.md
  src/pages/starter-kit/integration/events.md
  src/pages/starter-kit/integration/receive-data.md
  src/pages/starter-kit/integration/send-data.md
  src/pages/starter-kit/integration/webhooks.md
Labels: new-topic

#363 CEXT-4594: Add code samples for webhooks use cases
  src/data/navigation/sections/webhooks.js
  src/pages/app-development/learning-path.md
  src/pages/webhooks/index.md
  src/pages/webhooks/use-cases.md
  src/pages/webhooks/use-cases/check-gift-card-balance.md
  src/pages/webhooks/use-cases/code-samples/check-gift-card-balance-admin.md
  src/pages/webhooks/use-cases/code-samples/check-gift-card-balance-xml.md
  src/pages/webhooks/use-cases/code-samples/customer-address-mod-admin.md
  src/pages/webhooks/use-cases/code-samples/customer-address-mod-xml.md
  src/pages/webhooks/use-cases/code-samples/customer-address-validation-admin.md
  src/pages/webhooks/use-cases/code-samples/customer-address-validation-xml.md
  src/pages/webhooks/use-cases/code-samples/discount-code-validation-admin.md
  src/pages/webhooks/use-cases/code-samples/discount-code-validation-xml.md
  src/pages/webhooks/use-cases/code-samples/gift-card-validation-admin.md
  src/pages/webhooks/use-cases/code-samples/gift-card-validation-xml.md
  src/pages/webhooks/use-cases/code-samples/order-placement-validation-admin.md
  src/pages/webhooks/use-cases/code-samples/order-placement-validation-xml.md
  src/pages/webhooks/use-cases/code-samples/product-generate-content-admin.md
  src/pages/webhooks/use-cases/code-samples/product-generate-content-xml.md
  src/pages/webhooks/use-cases/code-samples/product-price-update-admin.md
  src/pages/webhooks/use-cases/code-samples/product-price-update-xml.md
  src/pages/webhooks/use-cases/code-samples/product-stock-validation-admin.md
  src/pages/webhooks/use-cases/code-samples/product-stock-validation-xml.md
  src/pages/webhooks/use-cases/code-samples/product-update-validation-admin.md
  src/pages/webhooks/use-cases/code-samples/product-update-validation-xml.md
  src/pages/webhooks/use-cases/customer-address-modification.md
  src/pages/webhooks/use-cases/customer-address-validation.md
  src/pages/webhooks/use-cases/discount-code-validation.md
  src/pages/webhooks/use-cases/gift-card-validation.md
  src/pages/webhooks/use-cases/index.md
  src/pages/webhooks/use-cases/order-placement-validation.md
  src/pages/webhooks/use-cases/product-generate-content.md
  src/pages/webhooks/use-cases/product-price-update.md
  src/pages/webhooks/use-cases/product-stock-validation.md
  src/pages/webhooks/use-cases/product-update-validation.md
Labels: internal, new-topic

#362 Clarify checkout starter kit auth
  src/pages/admin-ui-sdk/installation.md
  src/pages/starter-kit/checkout/connect.md
  src/pages/starter-kit/checkout/getting-started.md
Labels: editorial

#370 Fix: analytics tracking
  gatsby-browser.js
Labels: maintenance, internal

#372 Webhook formatting
  src/pages/starter-kit/checkout/payment-use-cases.md
Labels: editorial

#373 Improve formating of codeblocks in webhooks use cases
  src/pages/webhooks/use-cases/check-gift-card-balance.md
  src/pages/webhooks/use-cases/code-samples/check-gift-card-balance-admin.md
  src/pages/webhooks/use-cases/code-samples/customer-address-mod-admin.md
  src/pages/webhooks/use-cases/code-samples/customer-address-validation-admin.md
  src/pages/webhooks/use-cases/code-samples/discount-code-validation-admin.md
  src/pages/webhooks/use-cases/code-samples/gift-card-validation-admin.md
  src/pages/webhooks/use-cases/code-samples/order-placement-validation-admin.md
  src/pages/webhooks/use-cases/code-samples/product-generate-content-admin.md
  src/pages/webhooks/use-cases/code-samples/product-price-update-admin.md
  src/pages/webhooks/use-cases/code-samples/product-stock-validation-admin.md
  src/pages/webhooks/use-cases/code-samples/product-update-validation-admin.md
  src/pages/webhooks/use-cases/customer-address-modification.md
  src/pages/webhooks/use-cases/customer-address-validation.md
  src/pages/webhooks/use-cases/discount-code-validation.md
  src/pages/webhooks/use-cases/gift-card-validation.md
  src/pages/webhooks/use-cases/order-placement-validation.md
  src/pages/webhooks/use-cases/product-generate-content.md
  src/pages/webhooks/use-cases/product-price-update.md
  src/pages/webhooks/use-cases/product-stock-validation.md
  src/pages/webhooks/use-cases/product-update-validation.md
Labels: editorial, internal

#338 Tax starter kit
  src/_includes/checkout-version.md
  src/data/navigation/sections/checkout-starter-kit.js
  src/pages/_images/starterkit/tax-management-ui.png
  src/pages/starter-kit/checkout/configure.md
  src/pages/starter-kit/checkout/connect.md
  src/pages/starter-kit/checkout/development.md
  src/pages/starter-kit/checkout/eds.md
  src/pages/starter-kit/checkout/getting-started.md
  src/pages/starter-kit/checkout/payment-install.md
  src/pages/starter-kit/checkout/payment-reference.md
  src/pages/starter-kit/checkout/payment-usage.md
  src/pages/starter-kit/checkout/payment-use-cases.md
  src/pages/starter-kit/checkout/shipping-install.md
  src/pages/starter-kit/checkout/shipping-reference.md
  src/pages/starter-kit/checkout/shipping-usage.md
  src/pages/starter-kit/checkout/shipping-use-cases.md
  src/pages/starter-kit/checkout/tax-install.md
  src/pages/starter-kit/checkout/tax-reference.md
  src/pages/starter-kit/checkout/tax-usage.md
  src/pages/starter-kit/checkout/tax-use-cases.md
  src/pages/starter-kit/checkout/use-cases.md
  src/pages/starter-kit/integration/events.md
  src/pages/starter-kit/integration/receive-data.md
  src/pages/starter-kit/integration/send-data.md
  src/pages/starter-kit/integration/webhooks.md
  static/tax.xml
Labels: new-topic

#377 CEXT-4676: Update the documentation with webhook context section
  src/pages/webhooks/hooks.md
Labels: internal, major-update
