Repository AdobeDocs/commerce-extensibility, pull requests merged in 2025-01, with the labels that each got.

#309 Clarify Admin UI SDK sandbox option and eligible workspace
  src/pages/admin-ui-sdk/configuration.md
Labels: editorial, internal

#307 CEXT-3974/CEXT-3975: Documentation for event update and unsubscribe endpoints
  src/pages/events/api.md
Labels: internal, major-update

#306 CEXT-3925: Get all subscribed events & webhook endpoint
  src/data/navigation/sections/webhooks.js
  src/pages/events/api.md
  src/pages/webhooks/api.md
Labels: internal, major-update

#312 CEXT-4033: Eventing 1.11 & webhooks 1.8 release notes
  src/pages/events/api.md
  src/pages/events/module-development.md
  src/pages/events/release-notes.md
  src/pages/webhooks/release-notes.md
Labels: internal, major-update

#315 CEXT-4103: Document oope-shipping-methods module
  src/pages/starter-kit/checkout/configure.md
  src/pages/starter-kit/checkout/getting-started.md
  src/pages/starter-kit/checkout/reference.md
  src/pages/starter-kit/checkout/use-cases.md
Labels: major-update
