Repository AdobeDocs/commerce-extensibility, pull requests merged in 2025-07, with the labels that each got.

#408 Update Admin UI SDK documentation
  src/pages/admin-ui-sdk/app-registration.md
  src/pages/admin-ui-sdk/configuration.md
Labels: internal, technical, feedback

#410 CEXT-4921: clarify event configuration step
  src/pages/starter-kit/checkout/configure.md
  src/pages/starter-kit/checkout/development.md
Labels: major-update

#415 checkout-starter-kit: Fix wrong payment api & commerce integrations precedence
  src/pages/starter-kit/checkout/connect.md
  src/pages/starter-kit/checkout/payment-reference.md
Labels: editorial

#417 API service update and dropin images
  src/pages/_images/starterkit/eds-components.png
  src/pages/app-development/app-submission-guidelines.md
  src/pages/app-development/extension-compatibility.md
  src/pages/starter-kit/checkout/eds.md
  src/pages/starter-kit/integration/create-integration.md
Labels: major-update, feedback

#385 webhook-appbuilder-tutorial
  src/data/navigation/sections/webhooks.js
  src/pages/_images/webhooks/tutorial/debug-actions-option.png
  src/pages/_images/webhooks/tutorial/developer-access-dev-console.png
  src/pages/_images/webhooks/tutorial/developer-console-oauth-commerce.png
  src/pages/_images/webhooks/tutorial/restrcited-access-developer-console.png
  src/pages/_images/webhooks/tutorial/webhook-logs-adminui-accs.png
  src/pages/webhooks/tutorial/best-practices.md
  src/pages/webhooks/tutorial/debug.md
  src/pages/webhooks/tutorial/index.md
  yarn.lock
Labels: new-topic

#420 fix: 404 in webhooks TOC
  src/data/navigation/sections/webhooks.js
Labels: editorial

#422 CEXT-5003: Release eventing modules
  src/pages/events/release-notes.md
Labels: internal, major-update

#423 node.js version
  src/pages/app-development/app-submission-guidelines.md
Labels: editorial
