Repository AdobeDocs/commerce-extensibility, pull requests merged in 2025-04, with the labels that each got.

#342 Add domain to skipUrlPatterns
  .remarkrc.mjs
Labels: maintenance

#343 CEXT-4516: Create an eventing multiprovider documentation
  src/data/navigation/sections/events.js
  src/pages/_images/events/multiprovider-create.png
  src/pages/_images/events/multiprovider-grid.png
  src/pages/events/api.md
  src/pages/events/commands.md
  src/pages/events/configure-additional-event-providers.md
  src/pages/events/release-notes.md
Labels: documentation, internal, new-topic

#346 Update sharedContext example
  src/pages/admin-ui-sdk/extension-points/index.md
Labels: internal, technical

#347 Fix typo, add link
  src/pages/admin-ui-sdk/release-notes.md
  src/pages/events/commands.md
Labels: editorial, internal

#348 CEXT-4524: Add ACCS event subscription docs
  src/data/navigation/sections/events.js
  src/pages/_images/events/edit-event-subscription.png
  src/pages/_images/events/event-subscription-settings.png
  src/pages/_images/events/events-subscriptions-grid.png
  src/pages/events/create-events.md
Labels: internal, new-topic

#349 Add ACCS webhooks Admin docs
  src/data/navigation/sections/webhooks.js
  src/pages/_images/webhooks/edit-hook-settings.png
  src/pages/_images/webhooks/new-hook-settings.png
  src/pages/_images/webhooks/test-webhook.png
  src/pages/_images/webhooks/webhooks-subscriptions-grid.png
  src/pages/webhooks/create-webhooks.md
  src/pages/webhooks/hooks.md
Labels: internal, new-topic

#345 Integration starter kit updates
  src/pages/starter-kit/integration/create-integration.md
Labels: major-update

#350 Adding ACCS note and updating use case organization
  src/pages/starter-kit/checkout/connect.md
  src/pages/starter-kit/checkout/getting-started.md
  src/pages/starter-kit/checkout/use-cases.md
Labels: major-update

#352 CCSAAS-861: shadow edition component
  README.md
  gatsby-browser.js
  gatsby-ssr.js
  src/@adobe/gatsby-theme-aio/components/Edition/index.js
  src/pages/events/create-events.md
  src/pages/starter-kit/checkout/getting-started.md
  src/pages/starter-kit/checkout/use-cases.md
  src/pages/starter-kit/integration/create-integration.md
  src/pages/webhooks/create-webhooks.md
Labels: enhancement

#355 Update Admin UI SDK install topic
  src/pages/admin-ui-sdk/installation.md
Labels: editorial, internal

#357 Change the date in the eventing release notes
  src/pages/events/release-notes.md
Labels: editorial, internal
