Repository AdobeDocs/commerce-extensibility, pull requests merged in 2025-09, with the labels that each got.

#443 Remvoe JWT references
  src/pages/_images/events/general-configuration-empty.png
  src/pages/events/configure-commerce.md
Labels: editorial

#444 remove spaces from skus
  src/pages/starter-kit/integration/webhooks.md
  src/pages/webhooks/use-cases/product-price-update.md
  src/pages/webhooks/use-cases/product-stock-validation.md
  src/pages/webhooks/use-cases/product-update-validation.md
Labels: editorial, feedback

#428 Extend Adobe Commerce with Events and App Builder ,a guide covering …
  src/data/navigation/sections/events.js
  src/pages/_images/events/tutorial/adobe-commerce-create-event-provider.png
  src/pages/_images/events/tutorial/adobe-console-event-registration-action.png
  src/pages/_images/events/tutorial/adobe-console-events-debug-tracer.png
  src/pages/_images/events/tutorial/adobe-io-events-integration-architecture.png
  src/pages/events/tutorial/debugging.md
  src/pages/events/tutorial/deployment.md
  src/pages/events/tutorial/event-providers.md
  src/pages/events/tutorial/index.md
Labels: internal, new-topic

#447 Fix broken link to experience league checkout drop-in page
  src/pages/starter-kit/checkout/eds.md
Labels: editorial

#449 fix: links in partner essentials topic
  src/pages/app-development/app-builder-partnership-essentials.md
Labels: editorial
